In [1]:
import torch
print(f"Is Available?: {torch.cuda.is_available()}")
print(f"Number of GPUs available: {torch.cuda.device_count()}")

Is Available?: True
Number of GPUs available: 2


/home/dmvaayuai/anaconda3/envs/deeplearning/lib/python3.11/site-packages/torch/cuda/__init__.py:628: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
tensor_1 = torch.tensor([1, 2, 3])
print(tensor_1, tensor_1.device)

tensor([1, 2, 3]) cpu


In [5]:
# Move the tensor to GPU if available
tensor_1_on_gpu = tensor_1.to(device)
tensor_1_on_gpu

tensor([1, 2, 3], device='cuda:0')

### If tensor is on GPU, can't transfer it to NumPy, to get it back to CPU use below command

In [7]:

tensor_1_back_to_cpu = tensor_1_on_gpu.cpu()
tensor_1_back_to_cpu

tensor([1, 2, 3])

### Converting tensor to numpy

In [9]:
tensor_1_to_numpy = tensor_1_back_to_cpu.numpy()
tensor_1_to_numpy

array([1, 2, 3])