In [15]:
import torch

In [16]:
# You may see the torch.Tensor() (capital T) constructor
# used in legacy code. This is an alias for
# the default tensor type torch.FloatTensor. You should
# instead use torch.tensor() to create your tensors.
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])
z = x + y
print(z)
print(z.size())

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])


In [17]:
device = "cuda" if torch.cuda.is_available() else "cpu"

You can use strings directly as device parameters instead of
device objects. The following are all equivalent:
- `device="cuda"`
- `device=torch.device("cuda")`
- `device="cuda:0"`
- `device=torch.device("cuda:0")`

In [18]:
x = torch.tensor([[1,2,3], [4,5,6]], device=device)
y = torch.tensor([[7,8,9], [10,11,12]], device=device)
z = x + y
print(z)
print(z.size())
print(z.device)

tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')
torch.Size([2, 3])
cuda:0


In [19]:
# Moving tensor 'z' back to CPU
z.to("cpu")

tensor([[ 8, 10, 12],
        [14, 16, 18]])

In [20]:
z.device

device(type='cuda', index=0)

In [21]:
# z.to("cpu") will create a new copy in cpu and hence 
# we need to re-assign z to the copy available in cpu
z = z.to("cpu")
z.device

device(type='cpu')