In [6]:
import torch

In [7]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)
print(x.shape)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
torch.Size([4, 3])


In [8]:
# Indexing, returns a tensor
x[1,1]

tensor(5)

In [9]:
# Indexing, returns a value as a Python number
x[1,1].item()

5

In [12]:
# [start:end:step] format
print(x[:2,0])

tensor([1, 4])


In [13]:
# Boolean indexing
# Only keep elements less than 5
print(x[x<5])

tensor([1, 2, 3, 4])


In [14]:
# Transpose array; x.t() or x.T can be used
print(x.t())

tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])


In [15]:
# Change shape; usually view() is preferred over
# reshape()
print(x.view(3,4))

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [18]:
# combine or split tensors by using functions like
# torch.stack() and torch.unbind(), respectively

# Combining tensors
y = torch.stack((x, x))
print(y)

# Splitting tensors
a, b, c = torch.unbind(x, dim=1)
print(a)
print(b)
print(c)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])
tensor([ 1,  4,  7, 10])
tensor([ 2,  5,  8, 11])
tensor([ 3,  6,  9, 12])


In [19]:
# item() is an important and commonly used function to
# return the Python number from a tensor containing a single
# value.

# • Use view() instead of reshape() for reshaping tensors in
# most cases. Using reshape() may cause the tensor to be
# copied, depending on its layout in memory. view()
# ensures that it will not be copied.

# • Using x.T or x.t() is a simple way to transpose 1D or 2D
# tensors. Use transpose() when dealing with multidimensional
# tensors.

# • The torch.squeeze() function is used often in deep learning
# to remove an unused dimension. For example, a batch
# of images with a single image can be reduced from 4D to
# 3D using squeeze().

# • The torch.unsqueeze() function is often used in deep
# learning to add a dimension of size 1. Since most PyTorch
# models expect a batch of data as an input, you could apply
# unsqueeze() when you only have one data sample. For
# example, you can pass a 3D image into torch.unsqueeze()
# to create a batch of one image.