In [2]:
import numpy as np
from numpy import ndarray

In [3]:
arr1_1d = np.array([1, 2, 3])
arr2_1d = np.array([4, 5, 6])
print(f"sum: {arr1_1d + arr2_1d}")
print(f"product: {arr1_1d * arr2_1d}")

sum: [5 7 9]
product: [ 4 10 18]


In [4]:
arr1_1d.shape

(3,)

In [5]:
# sum along different axis
arr3_2d = np.array([[1,2,3], 
                 [4,5,6]])
print(arr3_2d.shape)
print(f"sum along axis-0 i.e. row-wise: {arr3_2d.sum(axis=0)}")
print(f"sum along axis-1 i.e. column-wise: {arr3_2d.sum(axis=1)}")

(2, 3)
sum along axis-0 i.e. row-wise: [5 7 9]
sum along axis-1 i.e. column-wise: [ 6 15]


In [6]:
# square function
def sqr_of_ndarray(x: ndarray) -> ndarray:
     return np.power(x, 2)

In [7]:
# leaky relu
def leaky_relu(a: float, x: ndarray) -> ndarray:
    return np.maximum(a * x, x)

In [8]:
print(arr1_1d)
print(sqr_of_ndarray(arr1_1d))

[1 2 3]
[1 4 9]


In [9]:
print(arr1_1d)
print(leaky_relu(0.01, arr1_1d))

[1 2 3]
[1. 2. 3.]
