In [1]:
import numpy
import torch

In [10]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

In [6]:
# Tensors can be created from preexisting data stored in
# array-like structures such as lists, tuples, scalars, or serialized
# data files, as well as in NumPy arrays.

# Created from preexisting arrays
x = torch.tensor([1,2,3])
y = torch.tensor((4,5,6))
z = torch.tensor(numpy.array([10,11,12]))

print(x)
print(y)
print(z)

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([10, 11, 12])


In [8]:
# Initialized by size
a = torch.empty(2, 3)
b = torch.zeros(2, 3)
c = torch.ones(2, 3)

print(a)
print(b)
print(c)

tensor([[3.9497e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [15]:
# Initialized by size with random values
d = torch.rand(2, 3) # Creates a 2 × 3 tensor with elements from a uniform distribution on the interval [0, 1).
e = torch.randn(2, 3) # Elements are random numbers from a normal distribution with a mean of 0 and a variance of 1.
f = torch.randint(low=5, high=10, size=(2,3)) # Elements are random integers between 5 and 10.

print(d)
print(e)
print(f)

tensor([[0.0632, 0.0729, 0.1340],
        [0.5585, 0.1323, 0.7632]])
tensor([[-1.0476, -0.7610, -0.3156],
        [ 0.6731,  0.3520, -1.6593]])
tensor([[6, 6, 5],
        [5, 8, 8]])


In [11]:
# Initialized with specified data type or device
g = torch.empty(size=(2,3), dtype=torch.float64, device=device)
print(g)

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0', dtype=torch.float64)


In [14]:
# Initialized to have the same size, data type,
# and device as another tensor
h = torch.ones_like(g)
print(h)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', dtype=torch.float64)
