In [1]:
import torch

In [3]:
# all tensor elements have the same data type.
list_x = [[1,2,3], [4,5,6]]
x = torch.tensor(list_x, dtype=torch.float32)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [5]:
# Use the casting method to cast to a new data type
x.int() # x remains a float32 after the cast
x = x.int() # x changes to an int32 after the cast
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [6]:
# Use the to() method to cast to a new type
x = x.to(dtype=torch.float64)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [8]:
# Python automatically converts data types during
# operations
a = torch.tensor(data=[[1,2,3], [4,5,6]], dtype=torch.int32)
b = torch.tensor(data=[[7,8,9], [10,11,12]], dtype=torch.float32)
c = a + b
print(c)
print(c.dtype)

tensor([[ 8., 10., 12.],
        [14., 16., 18.]])
torch.float32


In [9]:
# To reduce space complexity, you may sometimes want to
# reuse memory and overwrite tensor values using in-place
# operations. To perform in-place operations, append the
# underscore (_) postfix to the function name. For example,
# the function y.add_(x) adds x to y, but the results will be
# stored in y.